### ISSUE TITLE
Fail scan action

### ISSUE THREAD

**Issue by hyeongguen-song** [ShiftLeftSecurity/scan-action#32]
The action seems to be failing, can you check what is the problem?

<details>
<summary>Traceback</summary>

```shell
Traceback (most recent call last):
  File "/usr/local/src/scan", line 786, in <module>
    main()
  File "/usr/local/src/scan", line 748, in main
    report_summary, build_status = analysis.summary(
  File "/usr/local/src/lib/analysis.py", line 121, in summary
    dep_data = get_depscan_data(drep_file)
  File "/usr/local/src/lib/analysis.py", line 45, in get_depscan_data
    dataList.append(json.loads(depline))
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line [33](https://github.com/x/y/actions/runs/3571818786/jobs/6022969884#step:4:34)7, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line [35](https://github.com/x/y/actions/runs/3571818786/jobs/6022969884#step:4:36)3, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
```

</details>

**Comment by prabhu** [comment]
@hyeongguen-song, could you check the JSON file produced by dep-scan and share the first two lines or let me know if you notice any issues there?

**Comment by hyeongguen-song** [comment]
@prabhu , Here are first two lines of `depscan-bom-report-python.json`
```json
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  ...
}
```

**Comment by prabhu** [comment]
Thank you. Scan image is being rebuilt with the fix. Give it another 10 mins

**Comment by hyeongguen-song** [comment]
<img width="1318" alt="스크린샷 2022-11-30 오후 4 59 22" src="https://user-images.githubusercontent.com/87850472/204739709-d654cdc3-1a6e-415b-bce2-370dd819737e.png">
It works well. Thanks a lot !
Please close isuue when you see this
